Adds first version of irrelevant
ahoraquesinosven/ui-registro-femicidios pull request #10
Opened 2024-07-03 02:25 UTC by giselamo

UI of https://ahoraquesinosven.atlassian.net/browse/OBK-11  
and https://github.com/ahoraquesinosven/api-registro-femicidios/pull/11

2024-07-06 03:22 UTC, giselamo commented
@andres-arana  agregue la opcion "volver a pendiente" para las notas irrelevantes. Estuvo probando varios flujos y anduvo ok. Podrás revisarlo porfa?

2024-07-10 02:14 UTC, andres-arana requested changes
LGTM excepto por una pequeña regression en el botón de asignar.

2024-07-10 02:14 UTC, andres-arana commented on src/routes/Feed.tsx
> -      }}>
Este cambio hace que el botón de asignar no abre más el un nuevo tab el link a la noticia.

2024-07-12 03:56 UTC, andres-arana approved these changes
LGTM

2024-07-12 03:58 UTC, merged